name: First GitHub Action

on:
  push:
    branches:
      - main
      - development
      - dev-ketan1
      - dev-ketan2

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "GitHub Actions is running successfully!"